### ISSUE TITLE
Lack of consideration about JWT/JWE/JWS

### ISSUE THREAD

**Issue by PauloASilva** [OWASP/API-Security#10]
Based on early feedback, a lack of consideration about JWT/JWE/JWS was pointed in A2:2019 Broken Authentication.

We would like to hear from the community whether this is a general feeling and request contributions on that matter.

@philippederyck maybe you can help us here?

Cheers,
Paulo A. Silva

**Comment by emilva** [comment]
+1, I think this should be included. Failing to verify JWT's is a common issue.

**Comment by philippederyck** [comment]
I would love to help, but I am swamped with a bunch of other things right now. However, I am following the topic, and if things crystallize into concrete action items, I'll see what I can do!

One thing to clear out is whether the JWT content belongs under authN or authZ ...

**Comment by caseysoftware** [comment]
Should this be a full blown section on "how to validate JWTs" or just a bullet point that it is mandatory? 

I would lean towards the second and leave "how to" guides as external references.

**Comment by philippederyck** [comment]
I agree on listing it with a couple of references. I have built an [overview cheat sheet](https://cheatsheets.pragmaticwebsecurity.com/jwt.html) about these issues, but an OWASP-style cheat sheet with more detail would be extremely useful!

**Comment by inonshk** [comment]
https://github.com/OWASP/API-Security/pull/18/files contains a section about JWT tokens
