### ISSUE TITLE
More about CORS misconfiguration

### ISSUE THREAD

**Issue by PauloASilva** [OWASP/API-Security#11]
Based on early feedback, a lack of consideration about CORS misconfiguration was pointed in A7:2019 Security Misconfiguration.

We would like to hear from the community whether this is a general feeling and request contributions on that matter.

We should keep in mind that we're addressing APIs in general and not on a browser-specific context.

@philippederyck maybe you can help us here?

Cheers,
Paulo A. Silva

**Comment by emilva** [comment]
I think it should be included, as it is definitely something a lot of developers have trouble implementing securely in their API's.

**Comment by philippederyck** [comment]
I would love to help, but I am swamped with a bunch of other things right now. However, I am following the topic, and if things crystallize into concrete action items, I'll see what I can do!

In my opinion, CORS belongs here whenever an API is exposed to a web frontend. Even in a mixed environment, the CORS aspect matters to secure web-based access. As @emilva points out, definitely an often misunderstood topic ...

Of course, if you want to keep the focus broad enough, I can see that CORS might be out of scope. A brief reference to it in a web context might suffice in that case.

**Comment by ThunderSon** [comment]
CORS is focused on **browsers** to protect the users from loading trusted APIs on untrusted domains. You can't separate them, unless I am missing a point.
Looking at [0xa7](https://github.com/OWASP/API-Security/blob/develop/2019/en/src/0xa7-security-misconfiguration.md), there doesn't seem to be any link to any CORS attack scenario, nor any way on how to fix them (link to a guide to fix it). This could be added maybe to the Secure Headers Project (SHP).

In the end, I'd recommend the addition of CORS in the below points:
- Attack Scenario (There are many between H1, and portswigger).
- How to prevent: a one liner.
- Link to a trusted article discussing CORS, unless it is added to the SHP
- [Testing CORS](https://www.owasp.org/index.php/Test_Cross_Origin_Resource_Sharing_(OTG-CLIENT-007)) This should soon be migrated to the GitHub generated www2, I'll keep it as a point over at the project if you see it as a viable thing to add.

What do you think about it?

**Comment by PauloASilva** [comment]
Hi @ThunderSon,
Please check [commit 7e178bc][1] which adds several of your recommendations to API7:2019 Security Misconfiguration.

Cheers,
Paulo A. Silva

[1]: https://github.com/OWASP/API-Security/commit/7e178bc76c76873e67ac46aeca73e03a8698664d

**Comment by ThunderSon** [comment]
Lookgs good! Thank you for the addition
