### ISSUE TITLE
OSSF passing - release notes for 2023

### ISSUE THREAD

**Issue by vanderaj** [OWASP/API-Security#115]
The OpenSSF badge requires release notes for the release. These don't currently exist.

"The project MUST provide, in each release, release notes that are a human-readable summary of major changes in that release to help users determine if they should upgrade and what the upgrade impact will be. The release notes MUST NOT be the raw output of a version control log (e.g., the "git log" command results are not release notes). Projects whose results are not intended for reuse in multiple locations (such as the software for a single website or service) AND employ continuous delivery MAY select "N/A". {N/A justification} {Met URL} [[release_notes](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.release_notes)]"

**Comment by ErezYalon** [comment]
@vanderaj, the necessity of the release notes is clear.
Regarding the badge, do we really need an OpenSSF badge for a document?

**Comment by PauloASilva** [comment]
The 2023 edition has a [Release Notes sections][1].
[Project releases][2] are tagged with a version number that include release notes too: e.g. [v2.2.0][3]

[1]: https://owasp.org/API-Security/editions/2023/en/0x04-release-notes/ 
[2]: https://github.com/OWASP/API-Security/tags
[3]: https://github.com/OWASP/API-Security/releases/tag/v2.2.0
