### ISSUE TITLE
OpenSSF passing - need a build script

### ISSUE THREAD

**Issue by vanderaj** [OWASP/API-Security#116]
There should be a way to produce the document using a build script. Preferably, this build script may wish to (re-)generate the published documents using a GitHub action, but that's up to you.

**Comment by PauloASilva** [comment]
[All available OWASP API Security Top 10 editions and their translations][1] are automatically built by [this GitHub Action][2].

[1]: https://owasp.org/API-Security/
[2]: https://github.com/OWASP/API-Security/blob/9c9a808215fcbebda9f657c12f3e572371697eb2/.github/workflows/ci.yml
