### ISSUE TITLE
Persian Translation for 2023

### ISSUE THREAD

**Issue by This-is-Neo** [OWASP/API-Security#124]
Hi Guys
I could contribute to translate the API TOP10 2023RC to Farsi/Persian & would want to know your opinion on this matter. We did the Persian translation for 2019 version as well.
@PauloASilva

**Comment by PauloASilva** [comment]
Hey,
You're more than welcome to translate the API Top 10 2023.
Note that the 2023 is not a Release Candidate (RC) anymore but the final version.

A quick how-to guide:

1. fork the official repository
2. create a translation branch `translation/fa` from the `master` branch
3. duplicate the `/editions/2023/en` folder (and its contents): `/editions/2023/fa`
4. translate the markdown files' content inside the new folder (`/editions/2023/fa`): categories' names should remain in english
5. edit the `/editions/2023/mkdocs.yml` adding an `alternate` language after the `English` one:
     ```
    - name: Farsi
       lang: fa
     ```

Please let me know in case you need further guidance.

Thanks for giving back to the community.

Cheers,
Paulo A. Silva

**Comment by This-is-Neo** [comment]
Thanks @PauloASilva, I'll deliver the project within a month or two at most and I'll do my best not to degrade the main material quality :)

**Comment by PauloASilva** [comment]
Hey @This-is-Neo,
How is this translation going?

Cheers,
Paulo A. Silva

**Comment by PauloASilva** [comment]
Hi @This-is-Neo ,
Please check [these changes][1], reviewing your translation to understand whether they apply. Nested lists should use 4 spaces indentation.

Cheers,
Paulo A. Silva

[1]: https://github.com/OWASP/API-Security/compare/v2.4.0...v2.4.1

**Comment by This-is-Neo** [comment]
Hi @PauloASilva,

I’m pleased to inform you that the Persian translation of the OWASP API Security Top 10 - 2023 is now complete. You can review the translation and access the changes in the following link: [Persian Translation PR](https://github.com/OWASP/API-Security/pull/134/commits/c2fe68cf697ee65ca5b4497a4f2010c1fe7e8782).

Please proceed with the publication when you have the chance. Let me know if there are any additional steps or adjustments needed before finalizing it.

Thank you for your support and assistance!

**Comment by This-is-Neo** [comment]
Hi @ErezYalon 
I’m pleased to inform you that the Persian translation of the OWASP API Security Top 10 - 2023 is now complete. You can review the translation and access the changes in the following link: [Persian Translation PR](https://github.com/OWASP/API-Security/pull/134/commits/c2fe68cf697ee65ca5b4497a4f2010c1fe7e8782).

Please proceed with the publication when you have the chance. Let me know if there are any additional steps or adjustments needed before finalizing it.

Thank you for your support and assistance!

**Comment by ErezYalon** [comment]
Thanks, @This-is-Neo , we are on it.

**Comment by PauloASilva** [comment]
Hi @This-is-Neo,
The Persian translation was released in [v2.6.0](https://github.com/OWASP/API-Security/releases/tag/v2.6.0) and should be online soon.

Thanks for giving back to the community :clap: 

Cheers,
Paulo A. Silva

**Comment by This-is-Neo** [comment]
Hi @PauloASilva 

Thank you so much! I'm glad the Persian translation has made it to release v2.6.0. It’s an honor to contribute and support the OWASP community, and I hope this translation will help even more developers and security enthusiasts access these important resources.

Cheers to the community and everyone involved! 🎉

Best regards,
