### ISSUE TITLE
Translation to French (fr) for 2023 version

### ISSUE THREAD

**Issue by Nounoursdestavernes** [OWASP/API-Security#129]
Hello there,

I would like to help on translating the project in French for the 2023 version.
I have already fork and create a new branch by following instructions detailed here : https://github.com/OWASP/API-Security/issues/124#issuecomment-1737308376 (I've seen that worked for https://github.com/OWASP/API-Security/issues/127#issue-2047661517 :-) )
I will work on translation on this repo : https://github.com/Nounoursdestavernes/API-Security

Best regards,
NounoursDesTavernes / Aurélien TRONCY.

**Comment by PauloASilva** [comment]
Hey folks,
French translation was released in [v2.4.0](https://github.com/OWASP/API-Security/releases/tag/v2.4.0) and it is already available :rocket: 

Thanks for giving back to the community!

Cheers,
Paulo A. Silva
