### ISSUE TITLE
Comments about Broken Authentication

### ISSUE THREAD

**Issue by emilva** [OWASP/API-Security#15]
I think the section about broken authentication needs to be more clear, examples and suggestion follows:

The section about "is the API vulnerable?" needs to be more specific. 
>The API is vulnerable if:
> - Authentication only relies on access tokens.

What does this really mean? Do we have any examples to clarify? Maybe the concept of "access token" needs to be defined in the introduction. 

>The API is vulnerable if:
> - The same access token is valid for multiple APIs or API versions.

Needs to be more specific with regards to multiple APIs. Why is it broken if two different APIs are using the same auth service?

>The API is vulnerable if
> - Access tokens are tracked together with the source code on a version control system or hard-coded in the client. 

I would not say that an API is vulnerable to broken authentication if it has bad secret management. The API is only vulnerable if the secrets in the source code is exposed. 

Suggestion to other points that can indicate that an API is vulnerable to broken authentication:

1.  If the authentication mechanism relies on random tokens, then the tokens should not be predictable.
2. If some value can be derived from the token itself, i.e.: in JWTs or where the value is an encrypted string, then it must be tamper-proof. 

When it comes to the attack scenarios and the "how to prevent" section, I feel it would be nice to tie them together. Example: if you need to do API requests on behalf on a user from a mobile app, what is the best practice? Providing suggested "fix" or best practice alongside the attack scenarios will be much more helpful.

**Comment by kozmic** [comment]
Great feedback from @emilva. I think the issues pointed are valid.

**Comment by inonshk** [comment]
Thanks for the feedback.
A2 was re-written and I addressed most of the points that you mentioned:
https://github.com/OWASP/API-Security/pull/18/files
