### ISSUE TITLE
Translation pt-BR

### ISSUE THREAD

**Issue by PauloASilva** [OWASP/API-Security#30]
There's an ongoing `pt-BR` translation led by @raphaelhagi:

* [Mailing list thread][1]
* [GitHub Fork][2]

[1]: https://groups.google.com/a/owasp.org/d/msg/api-security-project/dDUxhNt0_dY/JsS78FMpBAAJ
[2]: https://github.com/raphaelhagi/API-Security

**Comment by raphaelhagi** [comment]
Currently workin on.
@PauloASilva, we need the original images for .odt file.
The first one is for cover, with the bee, to translate some words there.
The second image is that image used on header of each issue.
Is it possible? Thank you.

**Comment by PauloASilva** [comment]
Hi @raphaelhagi,
Nice to hear from you.

Regarding the weaknesses header, you'll be able to edit them: double-click to edit the text or right-click to Ungroup the elements.

The original cover is tracked in the repo: [check here](https://github.com/OWASP/API-Security/blob/master/2019/en/src/images/cover.jpg).
The best I can do to help you is to use my GIMP skills to remove the text so that you can then add it in the `.odt`. Do you want me to do it for you?

Cheers,
Paulo A. Silva

**Comment by PauloASilva** [comment]
Please check whether this works:
![cover](https://user-images.githubusercontent.com/2962581/76012476-3f09a900-5f0e-11ea-9957-5bbf32823e77.jpg)

If it gets the job done I'll replace it also in the `en` version.

Cheers,
Paulo A. Silva

**Comment by raphaelhagi** [comment]
Mate, this is awesome! Thanks.
I can put it on /en directory too, when I send to you via PR, it's done.
Thank you.

**Comment by PauloASilva** [comment]
> Mate, this is awesome! Thanks.
> I can put it on /en directory too, when I send to you via PR, it's done.
> Thank you.

@raphaelhagi I did it already and released a hotfix [v1.1.2].

Check out the new `.odt`: now you should be able to translate the cover subtitle.

Cheers,
Paulo A. Silva


[v1.1.2]: https://github.com/OWASP/API-Security/releases/tag/v1.1.2

**Comment by raphaelhagi** [comment]
I think we are very close to the final version. 
@PauloASilva when you work on translations, I see that you work on pt-PT translation, you also translate the issue title? I thought about it, and I tend to preserve original name.

**Comment by PauloASilva** [comment]
Hi @raphaelhagi,
We did it in the last OWASP Top 10 2017 pt-PT translation, but I see your point and we can take a different direction.

Since we're the first ones working on OWASP API Security Top 10 translations we can establish the guidelines. @leonelquinteros what do you think about this?

Cheers,
Paulo A. Silva

**Comment by leonelquinteros** [comment]
@PauloASilva @raphaelhagi I'm also translating the issue title. I agree it sounds weird translated, but the idea is to provide this information to people that don't understand english. 

What I would do in that case, is to have both, the translated title and the original one, somehow.

**Comment by raphaelhagi** [comment]
Wow, maintain translated and the original one makes sense. I'll try it on my translation and show it to you guys.

I thought about it because even the references bellow each issue have the original name, and, if somebody needs do go further with studies, they need to know English and the original name can be helpful to research.

For me, the purpose of translation is to make it easier to comprehend and reach more people.

**Comment by raphaelhagi** [comment]
Hello guys,
I'm ready for pull request. But I didn't found a branch for pt-BR translation.

**Comment by PauloASilva** [comment]
Hi Raphael,
Please go ahead and open a PR to the master branch.

Cheers,

A quinta, 26/03/2020, 21:53, Raphael Hagi <notifications@github.com>
escreveu:

**Comment by raphaelhagi** [comment]
All right, I did it.

**Comment by PauloASilva** [comment]
Hi @raphaelhagi,
the pt-BR translation is now available since [v1.2.0](https://github.com/OWASP/API-Security/releases/tag/v1.2.0).

Congrats to you and all pt-BR team.

Cheers,
Paulo A. Silva
