### ISSUE TITLE
Translation fr

### ISSUE THREAD

**Issue by datakime** [OWASP/API-Security#35]
Hi, 

Would you like the OWASP API Security Top 10 to be translated into French? If so, I would be pleased to do it and submit a PR when the translation is ready.

**Comment by PauloASilva** [comment]
Hi @datakime,
As far as we know there's no one else doing it, so you can start and lead the effort.

Someone else wanting to contribute, please comment here, so that @datakime can coordinate the work to be done.

Cheers,
Paulo A. Silva

**Comment by datakime** [comment]
Hi @PauloASilva,

Ok great, I'm on it with anybody who wishes to contribute.

**Comment by PauloASilva** [comment]
@datakime while we don't have official translation guidelines, please check other open/closed translation issues: you'll find there some relevant tips.

**Comment by datakime** [comment]
Hi @PauloASilva, the translation in md files is almost finished

**Comment by llegaz** [comment]
Hello, I could help review the translation if you need french readers.

**Comment by PauloASilva** [comment]
Hi @datakime, nice to hear that.

@llegaz I am sure @datakime and who-else is working in the FR translation will appreciate your help: please feel free to do it and commenting/suggest changes/opening pull requests whenever required.

Thanks you both for your contributions,
Paulo A. Silva

**Comment by datakime** [comment]
Hi @PauloASilva,

I eventually managed to finish the initial translation which I also proof-read a couple of times.

If @llegaz is still willing to review it, you can find them [in this folder of my fork](https://github.com/datakime/API-Security/tree/translation/fr-fr/2019/fr/src).

Please note that I haven't processed the distribution files yet. I will dot it once the translation will be considered final.

**Comment by PauloASilva** [comment]
Great job!
I am eager to merge your Pull Request.

**Comment by llegaz** [comment]
Hello @datakime,

First of all great work and thanks you for your translation. Secondly, I have started reviewing your work but is there a way I can add some comments and suggestions to it ? Maybe you could open a pull request here or in your personal folder ? It would be easier then to give comments on it.

Thanks

**Comment by llegaz** [comment]
@datakime I don't think so. I think it is better if you proceed as asked and propose a PR for you translation work. I don't know just take a look at the spanish PR, we are loosing time on this because of your "fork" way of doing and I will have to do twice the same work in the end... 

Please, use the tool in the appropriate way, it's easier for me to work on your PR and do a review because this is the way github (and its competitors) have been designed. Furthermore, we will all be able to keep track of what is discussed or modified, reforking your own fork in order to work on it for me is a total nonsense.

Moreover it is even stated in the document itself, remember : _"The OWASP API Security Top 10 2019 was first presented in the OWASP Global AppSec Tel Aviv event (May 2019). Since then, it has been **available on GitHub for public discussion and contributions**."_  So there are no real reasons to make discussion private even on french translation topic.

And finally, I'm pretty sure @PauloASilva will agree with me on this. So, once again, please @datakime think in a communitarian way, thanks in advance.

Regards

**Comment by datakime** [comment]
@llegaz I will  surely do as @PauloASilva will see fit and follow his guidance to ease his work. Please note that my fork is public, open for issues and PR, so in line with what you quoted.

As mentionned above, I have not processed the distribution files yet, meaning that not everything in my fork is ready for a formal PR to the project repo, and that was on purpose to ease the work of reviewers. Otherwise they (you) would have to make double edits to both files (markdown and distribution files) for each and every suggestion. 

Please don't put the burden of losing time on me since I replied to your question same day 17 days ago, and was ready to work with you  on this since then.

In any case, I will happily proceed whichever way @PauloASilva  prefers. Just let me know.

**Comment by PauloASilva** [comment]
Hi folks,
I really appreciate your enthusiasm and I would like to apologize: the lack of an automated build system to compile the distribution formats from the source may be creating some troubles.

@datakime if you're already comfortable with the markdown, please open the PR to the official repo: I won't accept it until the distribution formats are OK. Meanwhile @llegaz can provide feedback using the GitHub PR review feature, we can discuss them, and you'll be able to apply the required changes: the PR will be updated automatically.

After all required changes, distribution files should be updated accordingly. Once this is done, I'll merge your PR.

Once again, thank you for your contribution.
Let's keep the good work: I believe we're very close to finish this translation.

Cheers,
Paulo A. Silva

**Comment by datakime** [comment]
Thanks for the prompt reply @PauloASilva. PR opened to the official repo.

**Comment by llegaz** [comment]
@datakime Yes sorry for the delay, I was checking my mails daily for any news from you and got no notification.. When I came back from a family weekend I thought that it was weird and checked here and you had already replied for a long time.  ¯\_(ツ)_/¯

Anyway, I realize I have been a bit abrupt and I want to apologize. 
I wasn't really wanting to push you like this, all I wanted was the PR open for everyone, just in case some external people would join in or would check the reviewing and modification process in the future.

Best regards,
Laurent

**Comment by datakime** [comment]
Thanks for the clarification @llegaz. Your concern about keeping things open for everyone is legitimate, and I respect that. Looking forward to seing your review.

**Comment by llegaz** [comment]
@datakime Hi Fred, 

I've started reviewing you work and will try to finish it during the incoming week. We can discuss here or there for the little changes I've proposed so far.

Take care,
Laurent

**Comment by PauloASilva** [comment]
Hi Folks,
The French translation was merged and released ([v1.6.0]): I've done a small fix in the ODT/PDF regarding risk tables' headers.
The translation was added to the [Translations List]: please let me know if you want to change your name and/or profile page.

Congratulations for the final result and thanks for giving back!

Cheers,
Paulo A. Silva

[v1.6.0]: https://github.com/OWASP/API-Security/releases/tag/v1.6.0
[Translations List]: https://owasp.org/www-project-api-security/#div-translations
