### ISSUE TITLE
Translation in Greek

### ISSUE THREAD

**Issue by athanasiosem** [OWASP/API-Security#55]
Hello there!

I will be more than happy to create a translation in Greek language. I'm a Software Engineer from Greece.

**Comment by PauloASilva** [comment]
Hi @athanasiosem,
I'm assigning this issue to you so that you can coordinate and manage the translation effort if someone else wants to join your effort.

Thanks for giving back,
Paulo A. Silva

**Comment by athanasiosem** [comment]
Hi all!

Just to let you know that we have been working on this task for the past 5 months and we are aiming to issue a pull request with the Greek translation in roughly 2-3 months from now.

**Comment by PauloASilva** [comment]
@athanasiosem thanks for letting us know.

**Comment by athanasiosem** [comment]
The Greek translation has now finished! Please check Pull Request https://github.com/OWASP/API-Security/pull/73.
