### ISSUE TITLE
SSRF mitigations using denylists

### ISSUE THREAD

**Issue by 247arjun** [OWASP/API-Security#63]
While the **How to Prevent** section in the documentation calls out the use of allowlists, in practice it is often infeasible to "lockdown" network access due to the possibility of inadvertently blocking legitimate usage. In such cases, a deny list can help reduce attack surface.

**Comment by PauloASilva** [comment]
Hi @247arjun,
Thanks for taking the time to review the document and provide feedback.

I understand your point, nevertheless denylists are hard to build and maintain, making them almost never a recommendation you would want to give.

Let's say your API expected a git URL and then, behind the scene, it goes and fetches metadata and pulls source code.
What would a denylist be on day zero? How would you update/maintain the denylist?

On day zero, the allowlist should be well-defined by the business requirement for such a feature: "*As a business we want to allow API clients to fetch metada/pull source code from GitHub, GitLab, Bitbucket, etc...*". Changing the business requirement means an allowlist update.

Not sure whether you had the chance to read the [Server-Side Request Forgery Prevention Cheat Sheet][1]: if not I greatly recommend it.

Cheers,
Paulo A. Silva

[1]: https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html
