### ISSUE TITLE
API9:2023 Improper Inventory Management - link to a real website

### ISSUE THREAD

**Issue by gavjl** [OWASP/API-Security#75]
www.socialnetwork.com is a real website, should we have a fictional site instead? owasp.org? example.com?

**Comment by PauloASilva** [comment]
We should use a "fictional site" instead, nevertheless, at some point, someone may register the "fictional domain".

For sure we should avoid an hyperlink to be added by the markdown rendering engine to whatever "fictional domain" we may come up with: adding `` ` `` around the fictional domain should do it.

@gavjl would you like to open a pull request?

Cheers,
Paulo A. Silva
