### ISSUE TITLE
Question about the candidates

### ISSUE THREAD

**Issue by xplo1t-sec** [OWASP/API-Security#76]
Hello,

I have a small question about the release candidates. Are these the final categories that will be in the final release?

Thanks

**Comment by PauloASilva** [comment]
Hi @xplo1t-sec,

> Are these the final categories that will be in the final release?

Not necessarily.
These are the categories the OWASP API Security Project team came up with based on internal research and discussion.
They may change based on community feedback.

Cheers,
Paulo A. Silva

**Comment by xplo1t-sec** [comment]
Cool. Thanks for the response. I will try to contribute to this project from my side. 

Cheers
