### ISSUE TITLE
API3:2023 Broken Object Property Level Authorization - automatic binding of client input isn't necessarily bad

### ISSUE THREAD

**Issue by gavjl** [OWASP/API-Security#81]
In prevention it states - "If possible, avoid using functions that automatically bind a client's input into code variables, ..."

If a schema is used for incoming data then using a function to map that schema data onto the real objects is actually beneficial. Automatic binding of the complete object would be bad, but just the schema data is good - assuming the schema is well thought out of course!

**Comment by planetlevel** [comment]
Agree.  Automatic binding is good for security.  It prevents an insane amount of work in parsing data and manually populating objects.  Even binding the complete object is often just fine, as long as there are no object fields that shouldn't be exposed.  The only issue is when fields intended to be internal-only AND that are important in some way are overwritten with untrusted data.
