### ISSUE TITLE
API Lifecycle management

### ISSUE THREAD

**Issue by aymenfurter** [OWASP/API-Security#98]
Hi,

Perhaps within the [How to prevent section](https://github.com/OWASP/API-Security/blob/master/2023/en/src/0xa9-improper-assets-management.md#how-to-prevent) of Improper Inventory Management, a point covering proactive API Lifecycle management could be added? (i.e. • Implement API lifecycle management, actively sunsetting older, unused versions to ensure that only supported and secure versions are available for use)

**Comment by ErezYalon** [comment]
That is a good suggestion 👍 
Thanks!
